tag_prefix = "v"
pre_bump_hooks = [
    "cargo set-version --workspace {{version}}",
    "cargo metadata --format-version 1 > /dev/null",
    "scripts/bump-version {{version}}",
]

[changelog]
template = "remote"
remote = "github.com"
owner = "rtuszik"
repository = "WaxDemon"

[[changelog.authors]]
signature = "Robin Tuszik"
username = "rtuszik"
